spring.application.name=scrollserver

server.port=8080
server.address=0.0.0.0

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/mydbase

# JWT
app.jwt.secret=MyScrollApplicationSecretKey12345678901234567890
app.jwt.expiration=86400000